SAMPLE_RATE = 16000         # number of samples recorded (per second)
FRAME_MS = 30               # duration of one audio chunk (in millisecondss)
VAD_AGGRESSIVENESS = 0
MIN_SPEECH_MS = 100
SPEECH_HANGOVER_MS = 300     # tolerate pauses up to this long before ending an utterance
CLUSTER_THRESHOLD = 0.72
HISTORY_WINDOW = 1000
MODELS_DTR = "models/"
NEW_SPEAKER_TIME = 1.0